/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.38
 * Generated at: 2016-12-02 04:54:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.IOException;
import org.jsoup.select.Elements;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;

public final class bookmark_005fnews_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1480556566500L));
    _jspx_dependants.put("jar:file:/C:/Users/student/Desktop/workspace_tc/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/RealTimeNews/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.jsoup.nodes.Document");
    _jspx_imports_classes.add("java.io.IOException");
    _jspx_imports_classes.add("org.jsoup.select.Elements");
    _jspx_imports_classes.add("org.jsoup.Jsoup");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<!-- 위 3개의 메타 태그는 *반드시* head 태그의 처음에 와야합니다; 어떤 다른 콘텐츠들은 반드시 이 태그들 *다음에* 와야 합니다 -->\r\n");
      out.write("<title>북마크</title>\r\n");
      out.write("\r\n");
      out.write("<!-- 부트스트랩 -->\r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- 대쉬보드  -->\r\n");
      out.write("<link href=\"css/dashboard.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- IE8 에서 HTML5 요소와 미디어 쿼리를 위한 HTML5 shim 와 Respond.js -->\r\n");
      out.write("<!-- WARNING: Respond.js 는 당신이 file:// 을 통해 페이지를 볼 때는 동작하지 않습니다. -->\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("<!-- 모든 컴파일된 플러그인을 포함합니다 (아래), 원하지 않는다면 필요한 각각의 파일을 포함하세요 -->\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".yellow {\r\n");
      out.write("\tbackground-color: yellow;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".white {\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a.disabled {\r\n");
      out.write("\tpointer-events: none;\r\n");
      out.write("\tcursor: default;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* #dropdownMenu1 { */\r\n");
      out.write("/* \tbackground-color: black; */\r\n");
      out.write("/* \tborder-color: black; */\r\n");
      out.write("/* \theight: 50px; */\r\n");
      out.write("/* \tfont-size: normal; */\r\n");
      out.write("/* } */\r\n");
      out.write(".black {\r\n");
      out.write("\tbackground-color: #222222;\r\n");
      out.write("\tborder-color: #222222;\r\n");
      out.write("\theight: 50px;\r\n");
      out.write("\tfont-size: normal;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(" .commentBtn {\r\n");
      out.write(" \tbackground-color : #59B2E0;\r\n");
      out.write(" \toutline : none;\r\n");
      out.write(" \tcolor : #fff;\r\n");
      out.write(" \tfont-size : 14px;\r\n");
      out.write(" \theight : auto;\r\n");
      out.write(" \tfont-weight : normal;\r\n");
      out.write(" \tpadding : 10px 40px;\r\n");
      out.write(" \ttext-transform : uppercase;\r\n");
      out.write(" \tborder-color : #59B2E6;\r\n");
      out.write(" }\r\n");
      out.write(" body {\r\n");
      out.write(" \tfont-family : 'Malgun Gothic';\r\n");
      out.write(" \tfont-size : 10pt;\r\n");
      out.write(" }\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://code.jquery.com/jquery-3.1.1.js\"></script>\r\n");
      out.write("<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(\r\n");
      out.write("\t\t\tfunction() {\r\n");
      out.write("\t\t\t\tvar startRow = 0;\r\n");
      out.write("\t\t\t\tvar endRow = 10;\r\n");
      out.write("\t\t\t\tvar loginId = $('#loginid').val();\r\n");
      out.write("\t\t\t\tloadnews();\r\n");
      out.write("\t\t\t\tloadranking();\r\n");
      out.write("\t\t\t\tsetInterval(function() {\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\turl : \"naver.do\",\r\n");
      out.write("\t\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\t\t$(data).find('keyword').each(\r\n");
      out.write("\t\t\t\t\t\t\t\t\tfunction(index) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar ranking = $(this).find('ranking')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t.text();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar searchkey = $(this).find(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t'searchkey').text();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar i = index + 1;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t'table#naverrank tr:eq(' + i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ ') td:eq(' + (i - i)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ ')').text(ranking);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t'table#naverrank tr:eq(' + i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ ') td:eq('\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ (i - i + 1) + ')')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t.text(searchkey);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\terror : function() {\r\n");
      out.write("\t\t\t\t\t\t\talert(\"error\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t}, 1000);\r\n");
      out.write("\t\t\t\t$(window).scroll(function() {\r\n");
      out.write("\t\t\t\t\tvar dh = $(document).height();\r\n");
      out.write("\t\t\t\t\tvar wh = $(window).height();\r\n");
      out.write("\t\t\t\t\tvar wt = $(window).scrollTop();\r\n");
      out.write("\t\t\t\t\tif (wt + wh == dh) {\r\n");
      out.write("\t\t\t\t\t\tloadnews();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\tfunction loadnews() {\r\n");
      out.write("\t\t\t\t\t$\r\n");
      out.write("\t\t\t\t\t\t\t.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\turl : \"news.do\",\r\n");
      out.write("\t\t\t\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstartRow : startRow,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tendRow : endRow,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tloginId : loginId,\r\n");
      out.write("\t\t\t\t\t\t\t\t\taction : 'selectBookmark'\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tif (data != 'empty') {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(data)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t.find('news')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t.each(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar imgUrl = $(this)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.find(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'imgUrl')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.text();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar title = $(this)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.find(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'title')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.text();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar content = $(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tthis).find(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'content')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.text();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar press = $(this)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.find(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'press')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.text();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar mainTitle = $(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tthis)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.find(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'mainTitle')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.text();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar mainContent = $(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tthis)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.find(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'mainContent')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.text();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar keyword = $(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tthis).find(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'keyword')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.text();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar newsNo = $(this)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.find(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'newsNo')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.text();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar id = $(this)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.find('id')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.text();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar state = $(this)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.find(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'state')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.text();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar result = \"<tr>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += \"<td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \"<img src='\"+imgUrl +\"'>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += \"<td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ title\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += \"<td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ content\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += \"<td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tif (id == loginId\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&& state == 'true') {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += \"<button type='button' id='bookmarkbtn' class='btn btn-default btn-lg yellow' value='\"+newsNo+\"'>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += \"<span class='glyphicon glyphicon-bookmark'></span>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += \"</button>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += \"<button type='button' id='bookmarkbtn' class='btn btn-default btn-lg' value='\"+newsNo+\"'>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += \"<span class='glyphicon glyphicon-bookmark'></span>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += \"</button>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += \"<button type='button' id='detailbtn' class='btn btn-default btn-lg' value='\"+newsNo+\"'>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += \"<span class='glyphicon glyphicon-chevron-down'></span>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += \"</button>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += \"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += \"<tr id='detail\"+newsNo+ \"' style='display:none'>\";\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += \"<td colspan='4' align='center'>\"; //게시물 자세히 보기\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += \"<div style='padding-right: 100px; padding-left: 100px'>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += \"<div><b>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ mainTitle\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \"</b></div>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += \"<div>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ mainContent\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \"</div>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += \"<div>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ press\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \"</div>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += \"<div>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ keyword\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \"</div>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t//댓글\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += \"<div id='co_div\"+newsNo+\"'>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += \"<fieldset id='co_div\"+newsNo+\"'>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += \"<legend align='left' style='font-size: 12px;'>댓글 쓰기</legend>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += \"<input type='hidden' id='newsNo' value=\"+newsNo+\">\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += \"<textarea id='content_text\"+newsNo+\"' name='content' rows='3' cols='100' style='resize: none'></textarea>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += \"<div style='margin-top:3px;margin-bottom:3px;'>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += \"<button type='button' class='btn btn-info commentBtn' id='btnCo' value=\"+newsNo+\">등록</button>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += \"</div>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += \"</fieldset>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += \"</div>\";\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += \"<div id='emptycomment\"+newsNo+ \"' style='display:none' class='alert alert-info alert-dismissible' role='alert'>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += \"<strong>Sorry!</strong> 더 이상 댓글이 없습니다.\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += \"</div>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += \"<div style='margin-top:8px;'>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += \"<button type='button' class='moreCo btn btn-info commentBtn' id='10' value=\"+newsNo+\">더보기</button>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += \"</div>\";\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += \"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += \"</tr>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult += \"</tr>\";\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'table#newslist tbody tr:last')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.before(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstartRow += endRow;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\tif (data == 'empty') {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$('#emptynews').show();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\terror : function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\talert(\"error\");\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t//댓글 등록 버튼\r\n");
      out.write("\t\t\t\t$(document).on('click','#btnCo', function(){\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar newsNo = $(this).attr('value');\r\n");
      out.write("\t\t\t\t\tvar content = $('#content_text'+newsNo+'').val();\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\turl: \"co.do\",\r\n");
      out.write("\t\t\t\t\t\ttype: \"post\",\r\n");
      out.write("\t\t\t\t\t\tdata: \"action=writeco&content=\"+content+\"&newsNo=\"+newsNo,\r\n");
      out.write("\t\t\t\t\t\tdatatype: \"xml\",\r\n");
      out.write("\t\t\t\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t\t\t\tconsole.log(\"test:\"+data);\r\n");
      out.write("\t\t\t\t\t\t\t$(data).find('comment').each(function() {\r\n");
      out.write("\t\t\t\t\t\t\t\tvar id =\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(this).find('id').text();\r\n");
      out.write("\t\t\t\t\t\t\t\tvar content =\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(this).find('content').text();\r\n");
      out.write("\t\t\t\t\t\t\t\tvar writeDate =\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(this).find('writedate').text();\r\n");
      out.write("\t\t\t\t\t\t\t\tvar comment =\"<tr colspan='4'>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tcomment += \"<td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tcomment +=\"<div style='border: 1px dashed #48BAE4; height: auto; padding:10px;width: 650px;margin-top: 3px;'>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tcomment += \"<div>\" + \"<p style='font-weight:bold;' align='left'>\"+ id +\"</p>\"+\"</div>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tcomment += \"<div>\" + \"<p style='font-weight:normal;' align='left'>\"+ content + \"</p>\"+\"</div>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tcomment += \"<div>\" + \"<p style='font-weight:lighter;' align='left'>\"+ writeDate + \"</p>\"+\"</div>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tcomment += \"</div>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tcomment +=\"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tcomment +=\"</tr>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\tconsole.log('div#co_div'+newsNo+'');\r\n");
      out.write("\t\t\t\t\t\t\t\t$('fieldset#co_div'+newsNo+'').after(comment);\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\terror: function(exception){\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t$('#content_text'+newsNo+'').val('');\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\t//더보기 버튼\r\n");
      out.write("\t\t$(document).on('click','.moreCo', function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar newsNo = $(this).attr('value');\r\n");
      out.write("\t\t\tvar startRowComment = $(this).attr('id');\r\n");
      out.write("\t\t\tvar endRow = 10;\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl: \"co.do\",\r\n");
      out.write("\t\t\t\ttype: \"post\",\r\n");
      out.write("\t\t\t\tdata: \"action=viewListMore&newsNo=\"+newsNo+\"&startRowComment=\"+startRowComment+\"&endRow=\"+endRow,\r\n");
      out.write("\t\t\t\tdatatype: \"xml\",\r\n");
      out.write("\t\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t\tconsole.log(\"test:\"+data);\r\n");
      out.write("\t\t\t\t\tif (data != 'empty') {\r\n");
      out.write("\t\t\t\t\t\t$(data).find('comment').each(function() {\r\n");
      out.write("\t\t\t\t\t\t\tvar id =\r\n");
      out.write("\t\t\t\t\t\t\t\t$(this).find('id').text();\r\n");
      out.write("\t\t\t\t\t\t\tvar content =\r\n");
      out.write("\t\t\t\t\t\t\t\t$(this).find('content').text();\r\n");
      out.write("\t\t\t\t\t\t\tvar writeDate =\r\n");
      out.write("\t\t\t\t\t\t\t\t$(this).find('writeDate').text();\r\n");
      out.write("\t\t\t\t\t\t\tvar newsNo =\r\n");
      out.write("\t\t\t\t\t\t\t\t$(this).find('newsNo').text();\r\n");
      out.write("\t\t\t\t\t\t\tvar comment =\"<tr colspan='4'>\";\r\n");
      out.write("\t\t\t\t\t\t\tcomment += \"<td>\";\r\n");
      out.write("\t\t\t\t\t\t\tcomment +=\"<div class=moreComment style='border: 1px dashed #48BAE4; height: auto; padding:10px;width: 650px;margin-top: 3px;'>\";\r\n");
      out.write("\t\t\t\t\t\t\tcomment += \"<div>\" + \"<p style='font-weight:bold;' align='left'>\"+ id +\"</p>\"+\"</div>\";\r\n");
      out.write("\t\t\t\t\t\t\tcomment += \"<div>\" + \"<p style='font-weight:normal;' align='left'>\"+ content + \"</p>\"+\"</div>\";\r\n");
      out.write("\t\t\t\t\t\t\tcomment += \"<div>\" + \"<p style='font-weight:lighter;' align='left'>\"+ writeDate + \"</p>\"+\"</div>\";\r\n");
      out.write("\t\t\t\t\t\t\tcomment += \"</div>\";\r\n");
      out.write("\t\t\t\t\t\t\tcomment +=\"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\tcomment +=\"</tr>\";\r\n");
      out.write("\t\t\t\t\t\t\t$('div#co_div'+newsNo+'').append(comment);\r\n");
      out.write("\t\t\t\t\t\t\t$('button.moreCo[value='+newsNo+']').attr('id',Number(startRowComment)+10);\r\n");
      out.write("\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t} if (data == 'empty') {\r\n");
      out.write("\t\t\t\t\t\t$('#emptycomment'+newsNo).show();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror: function(exception){\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#content_text').val('');\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\t\tfunction loadranking() {\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\turl : \"naver.do\",\r\n");
      out.write("\t\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\t\tdataType : \"xml\",\r\n");
      out.write("\t\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\t\t$(data).find('keyword').each(\r\n");
      out.write("\t\t\t\t\t\t\t\t\tfunction(index) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar ranking = $(this).find('ranking')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t.text();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar searchkey = $(this).find(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t'searchkey').text();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar i = index + 1;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t'table#naverrank tr:eq(' + i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ ') td:eq(' + (i - i)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ ')').text(ranking);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t'table#naverrank tr:eq(' + i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ ') td:eq('\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ (i - i + 1) + ')')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t.text(searchkey);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\terror : function() {\r\n");
      out.write("\t\t\t\t\t\t\talert(\"error\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$(document).on('click','#detailbtn',function() {\r\n");
      out.write("\t\t\t\t\tvar newsNo = $(this).attr('value');\r\n");
      out.write("\t\t\t\t\t$('#detail' + newsNo).toggle();\r\n");
      out.write("\t\t\t\t\tif($('#detail'+newsNo).css('display')!=\"none\"){\r\n");
      out.write("\t\t\t\t\t\tvar startRow = 0;\r\n");
      out.write("\t\t\t\t\t\tvar endRow = 5;\r\n");
      out.write("\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\turl: \"/RealTimeNews/co.do\",\r\n");
      out.write("\t\t\t\t\t\t\ttype: \"post\",\r\n");
      out.write("\t\t\t\t\t\t\tdata: \"action=viewList&newsNo=\"+newsNo+\"&startRow=\"+startRow+\"&endRow=\"+endRow,\r\n");
      out.write("\t\t\t\t\t\t\tdatatype: \"xml\",\r\n");
      out.write("\t\t\t\t\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t\t\t\t\tconsole.log(\"test:\"+data);\r\n");
      out.write("\t\t\t\t\t\t\t\t$(data).find('comment').each(function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar id =\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(this).find('id').text();\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar content =\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(this).find('content').text();\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar writeDate =\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(this).find('writeDate').text();\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar list =\"<tr colspan='4'>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\tlist += \"<td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\tlist +=\"<div style='border: 1px dashed #48BAE4; height: auto; padding:10px;width: 650px;margin-top: 3px;'>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\tlist += \"<div>\" + \"<p style='font-weight:bold;' align='left'>\"+ id +\"</p>\"+\"</div>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\tlist += \"<div>\" + \"<p style='font-weight:normal;' align='left'>\"+ content + \"</p>\"+\"</div>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\tlist += \"<div>\" + \"<p style='font-weight:lighter;' align='left'>\"+ writeDate + \"</p>\"+\"</div>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\tlist += \"</div>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\tlist +=\"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\tlist +=\"</tr>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$('div#co_div'+newsNo+'').append(list);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t\t\tstartRow += endRow;\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\terror: function(exception){\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t$('div#co_div'+newsNo+' > tr').empty();\r\n");
      out.write("\t\t\t\t\t\t$('#emptycomment'+newsNo).hide();\r\n");
      out.write("\t\t\t\t\t\t$('button.moreCo[value='+newsNo+']').attr('id',10);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$(this).find('span').toggleClass(\"glyphicon glyphicon-chevron-down glyphicon glyphicon-chevron-up\");\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\t//북마크 버튼\r\n");
      out.write("\t\t\t\t$(document)\r\n");
      out.write("\t\t\t\t\t\t.on(\r\n");
      out.write("\t\t\t\t\t\t\t\t'click',\r\n");
      out.write("\t\t\t\t\t\t\t\t'#bookmarkbtn',\r\n");
      out.write("\t\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar newsNo = $(this).attr('value');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(this)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t.toggleClass(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"btn btn-default btn-lg btn btn-default btn-lg yellow\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\turl : \"news.do\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tnewsNo : newsNo,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tloginId : loginId,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\taction : 'bookmark'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsuccess : function() {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\terror : function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\talert(\"error\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t$('img').attr('src', 'image/logo_01.png');\r\n");
      out.write("\t\t\t\t$('img').attr('width', '150');\r\n");
      out.write("\t\t\t\t$('img').attr('height', '20');\r\n");
      out.write("\t\t\t\t$('#bookmark').on('click',function(){\r\n");
      out.write("\t\t\t\t\tlocation.href=\"news.do?action=viewBookmark\";\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\t$('#inputMessage').on('keypress',function(e){\r\n");
      out.write("\t\t\t\t\tif(e.which == 13){\r\n");
      out.write("\t\t\t\t\t\tsend();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t})\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<input type=\"hidden\" id=\"loginid\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t<nav class=\"navbar navbar-inverse navbar-fixed-top\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"member.do?action=main\"><img /></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"navbar\" class=\"navbar-collapse collapse\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" class=\"disabled\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-star white\"></i>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("님\r\n");
      out.write("\t\t\t\t\t\t\t안녕하세요!</a></li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn btn-default dropdown-toggle black\" type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"dropdownMenu1\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"glyphicon glyphicon-user white\"> </i>\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"dropdown-menu\" aria-labelledby=\"dropdownMenu1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"member.do?action=logout\">로그아웃</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"member.do?action=updateMember\">회원정보수정</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-default btn-lg black\" type=\"button\" id=\"bookmark\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"glyphicon glyphicon-bookmark white\"></i>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<form class=\"navbar-form navbar-center\" action='news.do'\r\n");
      out.write("\t\t\t\t\tmethod='post'>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name='searchkeyword' class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"Search...\"> <input type=\"hidden\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"search\" name=\"action\">\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-sm-3 col-md-2 sidebar\">\r\n");
      out.write("\t\t\t\t<table class=\"table table-hover\" id=\"naverrank\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>순위</td>\r\n");
      out.write("\t\t\t\t\t\t<td>검색어</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<!-- RANK1 -->\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<!-- RANK2 -->\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<!-- RANK3 -->\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<!-- RANK4 -->\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<!-- RANK5 -->\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<!-- RANK6 -->\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<!-- RANK7 -->\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<!-- RANK8 -->\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<!-- RANK9 -->\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<!-- RANK10 -->\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t<legend>miniChat</legend>\r\n");
      out.write("\t\t\t\t\t\t<textarea id=\"messageWindow\" rows=\"20\" cols=\"40\"\r\n");
      out.write("\t\t\t\t\t\t\treadonly=\"readonly\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t<br> <input type=\"text\" id=\"inputMessage\" />\r\n");
      out.write("\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<h2 class=\"sub-header\">이 시간 핫한 뉴스!</h2>\r\n");
      out.write("\t\t\t\t<div class=\"table-responsive\">\r\n");
      out.write("\t\t\t\t\t<table class=\"table table-hover\" id=\"newslist\">\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>이미지</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>제목</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>내용</th>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t<tr id='emptynews' style='display: none'>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan='4'>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"alert alert-info alert-dismissible\" role=\"alert\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<strong>Sorry!</strong> 더 이상 뉴스가 없습니다.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tvar loginId = $('#loginid').val();\r\n");
      out.write("\t\tvar webSocket = new WebSocket(\r\n");
      out.write("\t\t\t\t'ws://70.12.109.96:8088/RealTimeNews/broadcasting');\r\n");
      out.write("\t\tvar textarea = document.getElementById(\"messageWindow\");\r\n");
      out.write("\t\tvar inputMessage = document.getElementById('inputMessage');\r\n");
      out.write("\r\n");
      out.write("\t\twebSocket.onmessage = function(e) { //웹 소켓에서 메시지가 날라왔을 때 호출되는 이벤트\r\n");
      out.write("\t\t\tonMessage(event)\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\twebSocket.onopen = function(e) { //웹 소켓이 연결되었을 때 호출되는 이벤트\r\n");
      out.write("\t\t\tonOpen(event)\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\twebSocket.onerror = function(e) { //웹 소켓이 에러가 났을 때 호출되는 이벤트\r\n");
      out.write("\t\t\tonError(event)\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\tfunction onMessage(event) {\r\n");
      out.write("\t\t\tvar msg = JSON.parse(event.data);\r\n");
      out.write("\t\t\tswitch(msg.type){\r\n");
      out.write("\t\t\tcase \"message\":\r\n");
      out.write("\t\t\t\ttextarea.value += msg.id + \" : \"+ msg.text +\"\\n\";\r\n");
      out.write("\t\t\t\tbreak;\r\n");
      out.write("\t\t\tcase \"login\":\r\n");
      out.write("\t\t\t\ttextarea.value += msg.text +\"\\n\";\r\n");
      out.write("\t\t\t\tbreak;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction onOpen(event) {\r\n");
      out.write("\t\t\ttextarea.value += loginId +\"님이 입장하셨습니다.\\n\";\r\n");
      out.write("\t\t\tvar msg = {\r\n");
      out.write("\t\t\t\t\ttype : \"login\",\r\n");
      out.write("\t\t\t\t\ttext : loginId +\"님이 입장하셨습니다.\"\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\twebSocket.send(JSON.stringify(msg));\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction onError(event) {\r\n");
      out.write("\t\t\talert(event.data);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction send() {\r\n");
      out.write("\t\t\tvar msg = {\r\n");
      out.write("\t\t\t\ttype : \"message\",\r\n");
      out.write("\t\t\t\ttext : inputMessage.value,\r\n");
      out.write("\t\t\t\tid : loginId,\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\ttextarea.value += loginId + \" : \"+ inputMessage.value +\"\\n\";\r\n");
      out.write("\t\t\twebSocket.send(JSON.stringify(msg));\r\n");
      out.write("\t\t\tinputMessage.value = \"\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
