/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.38
 * Generated at: 2016-12-02 02:23:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.IOException;
import org.jsoup.select.Elements;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1480556566500L));
    _jspx_dependants.put("jar:file:/C:/Users/student/Desktop/workspace_tc/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/RealTimeNews/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.jsoup.nodes.Document");
    _jspx_imports_classes.add("java.io.IOException");
    _jspx_imports_classes.add("org.jsoup.select.Elements");
    _jspx_imports_classes.add("org.jsoup.Jsoup");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <!-- 위 3개의 메타 태그는 *반드시* head 태그의 처음에 와야합니다; 어떤 다른 콘텐츠들은 반드시 이 태그들 *다음에* 와야 합니다 -->\r\n");
      out.write("    <title>index</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- 부트스트랩 -->\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 대쉬보드  -->\r\n");
      out.write("\t<link href=\"css/dashboard.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\r\n");
      out.write("    <!-- IE8 에서 HTML5 요소와 미디어 쿼리를 위한 HTML5 shim 와 Respond.js -->\r\n");
      out.write("    <!-- WARNING: Respond.js 는 당신이 file:// 을 통해 페이지를 볼 때는 동작하지 않습니다. -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body {\r\n");
      out.write("    padding-top: 90px;\r\n");
      out.write("    background-color: white\r\n");
      out.write("}\r\n");
      out.write(".panel-login {\r\n");
      out.write("\tborder-color: #ccc;\r\n");
      out.write("\t-webkit-box-shadow: 0px 2px 3px 0px rgba(0,0,0,0.2);\r\n");
      out.write("\t-moz-box-shadow: 0px 2px 3px 0px rgba(0,0,0,0.2);\r\n");
      out.write("\tbox-shadow: 0px 2px 3px 0px rgba(0,0,0,0.2);\r\n");
      out.write("}\r\n");
      out.write(".panel-login>.panel-heading {\r\n");
      out.write("\tcolor: #00415d;\r\n");
      out.write("\tbackground-color: #fff;\r\n");
      out.write("\tborder-color: #fff;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("}\r\n");
      out.write(".panel-login>.panel-heading a{\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcolor: #666;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tfont-size: 15px;\r\n");
      out.write("\t-webkit-transition: all 0.1s linear;\r\n");
      out.write("\t-moz-transition: all 0.1s linear;\r\n");
      out.write("\ttransition: all 0.1s linear;\r\n");
      out.write("}\r\n");
      out.write(".panel-login>.panel-heading a.active{\r\n");
      out.write("\tcolor: navy;\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("}\r\n");
      out.write(".panel-login>.panel-heading hr{\r\n");
      out.write("\tmargin-top: 10px;\r\n");
      out.write("\tmargin-bottom: 0px;\r\n");
      out.write("\tclear: both;\r\n");
      out.write("\tborder: 0;\r\n");
      out.write("\theight: 1px;\r\n");
      out.write("\tbackground-image: -webkit-linear-gradient(left,rgba(0, 0, 0, 0),rgba(0, 0, 0, 0.15),rgba(0, 0, 0, 0));\r\n");
      out.write("\tbackground-image: -moz-linear-gradient(left,rgba(0,0,0,0),rgba(0,0,0,0.15),rgba(0,0,0,0));\r\n");
      out.write("\tbackground-image: -ms-linear-gradient(left,rgba(0,0,0,0),rgba(0,0,0,0.15),rgba(0,0,0,0));\r\n");
      out.write("\tbackground-image: -o-linear-gradient(left,rgba(0,0,0,0),rgba(0,0,0,0.15),rgba(0,0,0,0));\r\n");
      out.write("}\r\n");
      out.write(".panel-login input[type=\"text\"],.panel-login input[type=\"email\"],.panel-login input[type=\"password\"] {\r\n");
      out.write("\theight: 45px;\r\n");
      out.write("\tborder: 1px solid #ddd;\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("\t-webkit-transition: all 0.1s linear;\r\n");
      out.write("\t-moz-transition: all 0.1s linear;\r\n");
      out.write("\ttransition: all 0.1s linear;\r\n");
      out.write("}\r\n");
      out.write(".panel-login input:hover,\r\n");
      out.write(".panel-login input:focus {\r\n");
      out.write("\toutline:none;\r\n");
      out.write("\t-webkit-box-shadow: none;\r\n");
      out.write("\t-moz-box-shadow: none;\r\n");
      out.write("\tbox-shadow: none;\r\n");
      out.write("\tborder-color: #ccc;\r\n");
      out.write("}\r\n");
      out.write(".btn-login {\r\n");
      out.write("\tbackground-color: #59B2E0;\r\n");
      out.write("\toutline: none;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\theight: auto;\r\n");
      out.write("\tfont-weight: normal;\r\n");
      out.write("\tpadding: 10px 40px;\r\n");
      out.write("\ttext-transform: uppercase;\r\n");
      out.write("\tborder-color: #59B2E6;\r\n");
      out.write("}\r\n");
      out.write(".btn-login:hover,\r\n");
      out.write(".btn-login:focus {\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tbackground-color: #53A3CD;\r\n");
      out.write("\tborder-color: #53A3CD;\r\n");
      out.write("}\r\n");
      out.write(".forgot-password {\r\n");
      out.write("\ttext-decoration: underline;\r\n");
      out.write("\tcolor: #888;\r\n");
      out.write("}\r\n");
      out.write(".forgot-password:hover,\r\n");
      out.write(".forgot-password:focus {\r\n");
      out.write("\ttext-decoration: underline;\r\n");
      out.write("\tcolor: #666;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".forgot-id {\r\n");
      out.write("\ttext-decoration: underline;\r\n");
      out.write("\tcolor: #888;\r\n");
      out.write("}\r\n");
      out.write(".forgot-id:hover,\r\n");
      out.write(".forgot-id:focus {\r\n");
      out.write("\ttext-decoration: underline;\r\n");
      out.write("\tcolor: #666;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-register {\r\n");
      out.write("\tbackground-color: #1CB94E;\r\n");
      out.write("\toutline: none;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\theight: auto;\r\n");
      out.write("\tweight: auto;\r\n");
      out.write("\tfont-weight: normal;\r\n");
      out.write("\tpadding: 10px 40px;\r\n");
      out.write("\ttext-transform: uppercase;\r\n");
      out.write("\tborder-color: #1CB94A;\r\n");
      out.write("}\r\n");
      out.write(".btn-register:hover,\r\n");
      out.write(".btn-register:focus {\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tbackground-color: #1CA347;\r\n");
      out.write("\tborder-color: #1CA347;\r\n");
      out.write("}\r\n");
      out.write("/* /////////////////////////////////////////////////////////////////////////////////////////////// */\r\n");
      out.write(".animated {\r\n");
      out.write("  -webkit-animation-duration: 1s;\r\n");
      out.write("\t   -moz-animation-duration: 1s;\r\n");
      out.write("\t     -o-animation-duration: 1s;\r\n");
      out.write("\t        animation-duration: 1s;\r\n");
      out.write("\t-webkit-animation-fill-mode: both;\r\n");
      out.write("\t   -moz-animation-fill-mode: both;\r\n");
      out.write("\t     -o-animation-fill-mode: both;\r\n");
      out.write("\t        animation-fill-mode: both;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".animated.hinges {\r\n");
      out.write("\t-webkit-animation-duration: 2s;\r\n");
      out.write("\t   -moz-animation-duration: 2s;\r\n");
      out.write("\t     -o-animation-duration: 2s;\r\n");
      out.write("\t        animation-duration: 2s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".animated.slow {\r\n");
      out.write("\t-webkit-animation-duration: 3s;\r\n");
      out.write("\t   -moz-animation-duration: 3s;\r\n");
      out.write("\t     -o-animation-duration: 3s;\r\n");
      out.write("\t        animation-duration: 3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".animated.snail {\r\n");
      out.write("\t-webkit-animation-duration: 4s;\r\n");
      out.write("\t   -moz-animation-duration: 4s;\r\n");
      out.write("\t     -o-animation-duration: 4s;\r\n");
      out.write("\t        animation-duration: 4s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@-webkit-keyframes shake {\r\n");
      out.write("\t0%, 100% {-webkit-transform: translateX(0);}\r\n");
      out.write("\t10%, 30%, 50%, 70%, 90% {-webkit-transform: translateX(-10px);}\r\n");
      out.write("\t20%, 40%, 60%, 80% {-webkit-transform: translateX(10px);}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@-moz-keyframes shake {\r\n");
      out.write("\t0%, 100% {-moz-transform: translateX(0);}\r\n");
      out.write("\t10%, 30%, 50%, 70%, 90% {-moz-transform: translateX(-10px);}\r\n");
      out.write("\t20%, 40%, 60%, 80% {-moz-transform: translateX(10px);}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@-o-keyframes shake {\r\n");
      out.write("\t0%, 100% {-o-transform: translateX(0);}\r\n");
      out.write("\t10%, 30%, 50%, 70%, 90% {-o-transform: translateX(-10px);}\r\n");
      out.write("\t20%, 40%, 60%, 80% {-o-transform: translateX(10px);}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@keyframes shake {\r\n");
      out.write("\t0%, 100% {transform: translateX(0);}\r\n");
      out.write("\t10%, 30%, 50%, 70%, 90% {transform: translateX(-10px);}\r\n");
      out.write("\t20%, 40%, 60%, 80% {transform: translateX(10px);}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".shake {\r\n");
      out.write("\t-webkit-animation-name: shake;\r\n");
      out.write("\t-moz-animation-name: shake;\r\n");
      out.write("\t-o-animation-name: shake;\r\n");
      out.write("\tanimation-name: shake;\r\n");
      out.write("\tcolor: red;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".red{\r\n");
      out.write("\tcolor: red;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".success{\r\n");
      out.write("\tcolor: green;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$('#login-form-link').click(function(e) {\r\n");
      out.write("\t\t\t$(\"#login-form\").delay(100).fadeIn(100);\r\n");
      out.write("\t\t\t$(\"#register-form\").fadeOut(100);\r\n");
      out.write("\t\t\t$('#register-form-link').removeClass('active');\r\n");
      out.write("\t\t\t$(this).addClass('active');\r\n");
      out.write("\t\t\te.preventDefault();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$('#register-form-link').click(function(e) {\r\n");
      out.write("\t\t\t$(\"#register-form\").delay(100).fadeIn(100);\r\n");
      out.write("\t\t\t$(\"#login-form\").fadeOut(100);\r\n");
      out.write("\t\t\t$('#login-form-link').removeClass('active');\r\n");
      out.write("\t\t\t$(this).addClass('active');\r\n");
      out.write("\t\t\te.preventDefault();\r\n");
      out.write("\t\t});\r\n");
      out.write("//////////////////////////////////////////////////////////////////////////////////\r\n");
      out.write("\t\tvar checkId = false;\r\n");
      out.write("\t\tvar idFlag;\r\n");
      out.write("\t\t$('#joinId').keyup(function() {\r\n");
      out.write("\t\t\tvar id = $('#joinId').val();\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"/RealTimeNews/ajax.do\",\r\n");
      out.write("\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\tdata : \"action=checkId&id=\" + id,\r\n");
      out.write("\t\t\t\tdatatype : \"text\",\r\n");
      out.write("\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\tvar email = $('#joinEmail').val();\r\n");
      out.write("\t\t\t\t\tif (data == 'false') {\r\n");
      out.write("\t\t\t\t\t\t$('#joinId').css('background', 'red');\r\n");
      out.write("\t\t\t\t\t\tidFlag = \"isDuplicated\"\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t$('#joinId').css('background', 'lightgreen');\r\n");
      out.write("\t\t\t\t\t\tidFlag = \"isOk\";\r\n");
      out.write("\t\t\t\t\t}\t\t\t\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(exception) {\r\n");
      out.write("\t\t\t\t\talert(\"ajax id error : \" + exception.message);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction checkEmailFunction(email) {\r\n");
      out.write("\t\t\tvar re = /^(([^<>()\\[\\]\\\\.,;:\\s@\"]+(\\.[^<>()\\[\\]\\\\.,;:\\s@\"]+)*)|(\".+\"))@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$/;\r\n");
      out.write("    \t\treturn re.test(email);\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tvar checkEmail = false;\r\n");
      out.write("\t\tvar emailFlag;\r\n");
      out.write("\t\t$('#joinEmail').keyup(function() {\r\n");
      out.write("\t\t\tvar email = $('#joinEmail').val();\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"/RealTimeNews/ajax.do\",\r\n");
      out.write("\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\tdata : \"action=checkEmail&email=\" + email,\r\n");
      out.write("\t\t\t\tdatatype : \"text\",\r\n");
      out.write("\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\tif (checkEmailFunction(email) == false) {\r\n");
      out.write("\t\t\t\t\t\t$('#joinEmail').css('background', 'red');\r\n");
      out.write("\t\t\t\t\t\temailFlag = 'isWrongForm';\r\n");
      out.write("\t\t\t\t\t} else{\r\n");
      out.write("\t\t\t\t\t\tif (data == 'false') {\r\n");
      out.write("\t\t\t\t\t\t\t$('#joinEmail').css('background', 'red');\r\n");
      out.write("\t\t\t\t\t\t\temailFlag = 'isDuplicated';\r\n");
      out.write("\t\t\t\t\t\t} else if (data == 'true') {\r\n");
      out.write("\t\t\t\t\t\t\t$('#joinEmail').css('background', 'lightgreen');\r\n");
      out.write("\t\t\t\t\t\t\temailFlag = 'isOk';\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(exception) {\r\n");
      out.write("\t\t\t\t\talert(\"ajax email error : \" + exception.message);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t//////////////////////////////////////////////////////////////////////////////\r\n");
      out.write("\t\tfunction checkPassword(id, password) {\r\n");
      out.write("\t\t\tif (!/^[a-zA-Z0-9]{5,15}$/.test(password)) {\r\n");
      out.write("\t\t\t\t$('#pwCheckMessage').html('숫자와 영문자 조합으로 5~15자리를 사용해야 합니다.');\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tvar checkNumber = password.search(/[0-9]/g);\r\n");
      out.write("\t\t\tvar checkEnglish = password.search(/[a-z]/ig);\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (checkNumber < 0 || checkEnglish < 0) {\r\n");
      out.write("\t\t\t\t$('#pwCheckMessage').html('숫자와 영문자를 혼용하여야 합니다.');\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif (/(\\w)\\1\\1\\1/.test(password)) {\r\n");
      out.write("\t\t\t\t$('#pwCheckMessage').html('같은 문자를 4번 이상 사용하실 수 없습니다.');\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif (password.search(id) > -1) {\r\n");
      out.write("\t\t\t\t$('#pwCheckMessage').html('비밀번호에 아이디가 포함되었습니다.');\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$('#joinPassword').keyup(function() {\r\n");
      out.write("\t\t\tvar id = $('#joinId').val();\r\n");
      out.write("\t\t\tvar password = $('#joinPassword').val();\r\n");
      out.write("\t\t\tif (checkPassword(id, password) == true) {\r\n");
      out.write("\t\t\t\t$('#pwCheckMessage').html('사용가능한 비밀번호입니다.');\r\n");
      out.write("\t\t\t\t$('#pwCheckMessage').removeClass('shake')\r\n");
      out.write("\t\t\t\t$('#pwCheckMessage').addClass('success');\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$('#pwCheckMessage').removeClass('success')\r\n");
      out.write("\t\t\t\t$('#pwCheckMessage').addClass('red');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t$('#joinConfirm_password').keyup(\r\n");
      out.write("\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\tif ($('#joinPassword').val() == $('#joinConfirm_password').val() && $('#joinPassword').val() != \"\" && $('#joinConfirm_password').val() != \"\") {\r\n");
      out.write("\t\t\t\t\t\t$('#pwCheckMessage').html('비밀번호가 일치합니다.');\r\n");
      out.write("\t\t\t\t\t\t$('#pwCheckMessage').removeClass('shake')\r\n");
      out.write("\t\t\t\t\t\t$('#pwCheckMessage').addClass('success');\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t$('#pwCheckMessage').html('비밀번호가 일치하지 않습니다.');\r\n");
      out.write("\t\t\t\t\t\t$('#pwCheckMessage').removeClass('success')\r\n");
      out.write("\t\t\t\t\t\t$('#pwCheckMessage').addClass('red');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t$('#register-submit').click(function() {\r\n");
      out.write("\t\t\t$('#pwCheckMessage').html(\"\");\t\r\n");
      out.write("\t\t\t$('#pwCheckMessage').removeClass('shake animated red success');\t\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t$('#register-form').submit(\r\n");
      out.write("\t\t\tfunction() {\r\n");
      out.write("\t\t\t\tif ($('#joinId').val() == \"\"|| $('#joinId').val().length < 5) {\r\n");
      out.write("\t\t\t\t\t$('#pwCheckMessage').html('5글자 이상의 아이디를 입력해주세요.');\r\n");
      out.write("\t\t\t\t\t$('#pwCheckMessage').addClass('shake animated');\r\n");
      out.write("\t\t\t\t\t$('#joinId').focus();\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t} else if ($('#joinUsername').val() == \"\") {\r\n");
      out.write("\t\t\t\t\t$('#pwCheckMessage').html('이름을 입력해주세요.');\r\n");
      out.write("\t\t\t\t\t$('#pwCheckMessage').addClass('shake animated');\r\n");
      out.write("\t\t\t\t\t$('#joinUsername').focus();\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t} else if ($('#joinEmail').val() == \"\") {\r\n");
      out.write("\t\t\t\t\t$('#pwCheckMessage').html('이메일을 입력해주세요.');\r\n");
      out.write("\t\t\t\t\t$('#pwCheckMessage').addClass('shake animated');\r\n");
      out.write("\t\t\t\t\t$('#joineMail').focus();\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t} else if(emailFlag=='isWrongForm'){\r\n");
      out.write("\t\t\t\t\t$('#pwCheckMessage').html('이메일 형식을 확인해주세요.');\r\n");
      out.write("\t\t\t\t\t$('#pwCheckMessage').addClass('shake animated');\r\n");
      out.write("\t\t\t\t\t$('#joineMail').focus();\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t} else if(emailFlag=='isDuplicated'){\r\n");
      out.write("\t\t\t\t\t$('#pwCheckMessage').html('중복된 이메일입니다.');\r\n");
      out.write("\t\t\t\t\t$('#pwCheckMessage').addClass('shake animated');\r\n");
      out.write("\t\t\t\t\t$('#joineMail').focus();\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t} else if ($('#joinPassword').val() == \"\") {\r\n");
      out.write("\t\t\t\t\t$('#pwCheckMessage').html('Password을 입력해주세요.');\r\n");
      out.write("\t\t\t\t\t$('#pwCheckMessage').addClass('shake animated');\r\n");
      out.write("\t\t\t\t\t$('#joinPassword').focus();\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t} else if ($('#joinPassword').val() != ($('#joinConfirm_password').val())) {\r\n");
      out.write("\t\t\t\t\t$('#pwCheckMessage').html('비밀번호가 불일치합니다.');\r\n");
      out.write("\t\t\t\t\t$('#pwCheckMessage').addClass('shake animated');\r\n");
      out.write("\t\t\t\t\t$('#confirmPassword').focus();\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t} else if (!checkPassword($('#joinId').val(),$('#joinPassword').val())) {\r\n");
      out.write("\t\t\t\t\t$('#pwCheckMessage').addClass('shake animated');\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t} else if ($('#joinId').val().lenth < 5){\r\n");
      out.write("\t\t\t\t\t$('#pwCheckMessage').html('5글자 이상의 아이디를 입력하세요.');\r\n");
      out.write("\t\t\t\t\t$('#pwCheckMessage').addClass('shake animated');\r\n");
      out.write("\t\t\t\t\t$('#confirmPassword').focus();\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t} else if (idFlag == 'isDuplicated'){\r\n");
      out.write("\t\t\t\t\t$('#pwCheckMessage').html('중복된 아이디입니다.');\r\n");
      out.write("\t\t\t\t\t$('#pwCheckMessage').addClass('shake animated');\r\n");
      out.write("\t\t\t\t\t$('#confirmPassword').focus();\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t} else return true;\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t$('#login-submit').click(function() {\r\n");
      out.write("\t\t\t$('#loginCheckMessage').html('');\r\n");
      out.write("\t\t\t$('#loginCheckMessage').removeClass('shake animated');\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t$('#login-form').submit(function() {\r\n");
      out.write("\t\t\tif ($('#id').val() == \"\") {\r\n");
      out.write("\t\t\t\t$('#loginCheckMessage').html('ID를 입력해주세요.');\r\n");
      out.write("\t\t\t\t$('#loginCheckMessage').addClass('shake animated');\r\n");
      out.write("\t\t\t\t$('#joinId').focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t} else if ($('#password').val() == \"\") {\r\n");
      out.write("\t\t\t\t$('#loginCheckMessage').html('Password를 입력해주세요.');\r\n");
      out.write("\t\t\t\t$('#loginCheckMessage').addClass('shake animated');\r\n");
      out.write("\t\t\t\t$('#joinId').focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t} else\r\n");
      out.write("\t\t\t\treturn true;\r\n");
      out.write("\t\t})\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<center>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("    \t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-6 col-md-offset-3\">\r\n");
      out.write("\t\t\t\t<div class=\"panel panel-login\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"col-xs-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"active\" id=\"login-form-link\">Login</a>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"col-xs-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" id=\"register-form-link\">Register</a>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<form id=\"login-form\" action=\"member.do\" method=\"post\" role=\"form\" style=\"display: block;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"action\" value=\"login\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"id\" id=\"id\" tabindex=\"1\" class=\"form-control\" placeholder=\"ID\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tvalue='");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("'>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"password\" name=\"password\" id=\"password\" tabindex=\"2\" class=\"form-control\" placeholder=\"Password\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" tabindex=\"3\" class=\"\" name=\"remember\" id=\"remember\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"remember\"> Remember Me</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-6 col-sm-offset-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" name=\"login-submit\" id=\"login-submit\" tabindex=\"4\" class=\"form-control btn btn-login\" value=\"Log In\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"loginCheckMessage\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"member.do?action=forgotId\" tabindex=\"5\" class=\"forgot-id\">Forgot Id?</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"member.do?action=forgotPassword\" tabindex=\"5\" class=\"forgot-password\">Forgot Password?</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t<form id=\"register-form\" action=\"member.do\" method=\"post\" role=\"form\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"action\" value=\"join\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"id\" id=\"joinId\" tabindex=\"1\" class=\"form-control\" placeholder=\"ID\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"username\" id=\"joinUsername\" tabindex=\"1\" class=\"form-control\" placeholder=\"Username\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"email\" name=\"email\" id=\"joinEmail\" tabindex=\"1\" class=\"form-control\" placeholder=\"Email Address\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"password\" name=\"password\" id=\"joinPassword\" tabindex=\"2\" class=\"form-control\" placeholder=\"Password\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"password\" name=\"confirm_password\" id=\"joinConfirm_password\" tabindex=\"2\" class=\"form-control\" placeholder=\"Confirm Password\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"pwCheckMessage\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-6 col-sm-offset-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" name=\"register-submit\" id=\"register-submit\" tabindex=\"4\" class=\"form-control btn btn-register\" value=\"Register Now\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</center>\r\n");
      out.write("\r\n");
      out.write("    <!-- jQuery (부트스트랩의 자바스크립트 플러그인을 위해 필요합니다) -->\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js\"></script>\r\n");
      out.write("    <!-- 모든 컴파일된 플러그인을 포함합니다 (아래), 원하지 않는다면 필요한 각각의 파일을 포함하세요 -->\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /index.jsp(446,19) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cookie.rememberId != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cookie.rememberId.value}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /index.jsp(463,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login_flag==false}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<p class=\"shake animated\">로그인 정보를 확인해주세요.</p>");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    }
    return false;
  }
}
